version: "3.9"

services:
  web:
    build: ./django_ecomerce/
    container_name : web
    
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_ecomerce/:/app/
    ports:
      - 8000:8000

    restart: always
    # environment:
    #   - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    #   - DJANGO_ALLOWED_HOSTS=${DOMAIN}


  proxy:
    build: ./nginx
    container_name : proxy
    restart: always
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - ./data/certbot/conf:/etc/letsencrypt
    #   - ./data/certbot/www:/var/www/certbot
    # environment:
    #   - DOMAIN=${DOMAIN}